
'use client';

import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Loader2, ClipboardCopy, Download } from 'lucide-react';
import { Button } from './ui/button';
import { useToast } from '@/hooks/use-toast';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface ReportViewerDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  content: string;
  isLoading: boolean;
}

export function ReportViewerDialog({ open, onOpenChange, content, isLoading }: ReportViewerDialogProps) {
  const { toast } = useToast();

  const handleCopy = () => {
    if (!content) return;
    navigator.clipboard.writeText(content).then(
      () => {
        toast({
          title: 'Copied to clipboard',
        });
      },
      (err) => {
        console.error('Could not copy text: ', err);
        toast({
          title: 'Failed to copy',
          description: 'Could not copy text to clipboard.',
          variant: 'destructive',
        });
      }
    );
  };
  
  const handleDownload = () => {
    if (!content) return;
    try {
      const lines = content.split('\n');
      const titleLine = lines.find(line => line.startsWith('# ')) || 'AI Report';
      const safeTitle = titleLine
        .replace(/^#\s*/, '')
        .replace(/[^\w\s-]/g, '') // Remove invalid filename characters
        .trim()
        .replace(/\s+/g, '_'); // Replace spaces with underscores
      
      const filename = safeTitle.substring(0, 250) + '.md';

      const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast({
        title: 'Download started',
        description: 'Your report is being downloaded.',
      });
    } catch (error) {
       console.error('Download failed: ', error);
        toast({
          title: 'Download Failed',
          description: 'Could not prepare the report for download.',
          variant: 'destructive',
        });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl h-[80vh] flex flex-col">
        <DialogHeader>
          <div className="flex justify-between items-center">
            <div className="space-y-1.5">
              <DialogTitle>AI Execution Report</DialogTitle>
              <DialogDescription>
                This is the full report generated by the AI assistant.
              </DialogDescription>
            </div>
            <div className="flex items-center gap-2 ml-4 flex-shrink-0">
                <Button variant="outline" size="icon" onClick={handleDownload} disabled={isLoading || !content}>
                  <Download className="h-4 w-4" />
                  <span className="sr-only">Download Report</span>
                </Button>
                <Button variant="outline" size="icon" onClick={handleCopy} disabled={isLoading || !content}>
                  <ClipboardCopy className="h-4 w-4" />
                  <span className="sr-only">Copy Report</span>
                </Button>
            </div>
          </div>
        </DialogHeader>
        <div className="flex-1 min-h-0">
          <ScrollArea className="h-full rounded-md border">
            {isLoading ? (
              <div className="flex items-center justify-center h-full">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
              </div>
            ) : (
              <article className="prose prose-sm dark:prose-invert max-w-none p-4">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {content}
                </ReactMarkdown>
              </article>
            )}
          </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  );
}
