'use client';

import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Loader2, ClipboardCopy } from 'lucide-react';
import { Button } from './ui/button';
import { useToast } from '@/hooks/use-toast';

interface ReportViewerDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  content: string;
  isLoading: boolean;
}

export function ReportViewerDialog({ open, onOpenChange, content, isLoading }: ReportViewerDialogProps) {
  const { toast } = useToast();

  const handleCopy = () => {
    if (!content) return;
    navigator.clipboard.writeText(content).then(
      () => {
        toast({
          title: 'Copied to clipboard',
        });
      },
      (err) => {
        console.error('Could not copy text: ', err);
        toast({
          title: 'Failed to copy',
          description: 'Could not copy text to clipboard.',
          variant: 'destructive',
        });
      }
    );
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl h-[80vh] flex flex-col">
        <DialogHeader>
          <div className="flex justify-between items-center">
            <div className="space-y-1.5">
              <DialogTitle>AI Execution Report</DialogTitle>
              <DialogDescription>
                This is the full report generated by the AI assistant.
              </DialogDescription>
            </div>
            <Button variant="outline" size="icon" onClick={handleCopy} disabled={isLoading || !content} className="ml-4 flex-shrink-0">
              <ClipboardCopy className="h-4 w-4" />
              <span className="sr-only">Copy Report</span>
            </Button>
          </div>
        </DialogHeader>
        <div className="flex-1 min-h-0">
          <ScrollArea className="h-full rounded-md border p-4">
            {isLoading ? (
              <div className="flex items-center justify-center h-full">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
              </div>
            ) : (
              <div className="text-sm text-foreground whitespace-pre-wrap font-code">
                {content}
              </div>
            )}
          </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  );
}
